In [25]:
import pandas as pd
import numpy as np
import sklearn as sl
import matplotlib.pyplot as pl

In [26]:
df=pd.read_excel("USA.xlsx")#Leemos el fichero xlsx

In [27]:
df

Ciudad    SO2  Neg.Temp  Empresas  Poblacion  Viento  Precip  \
0               Phoenix   10.0      70.3     213.0      582.0     6.0    7.05   
1           Little Rock   13.0      61.0      91.0      132.0     8.2   48.52   
2         San Francisco   12.0      56.7     453.0      716.0     8.7   20.66   
3                Denver   17.0      51.9     454.0      515.0     9.0   12.95   
4              Hartford   56.0      49.1     412.0      158.0     9.0   43.37   
5            Wilmington   36.0      54.0      80.0       80.0     9.0   40.25   
6            Washington   29.0      57.3     434.0      757.0     9.3   38.89   
7          Jacksonville   14.0      68.4     136.0      529.0     8.8   54.47   
8                 Miami   10.0      75.5     207.0      335.0     9.0   59.80   
9               Atlanta   24.0      61.5     368.0      497.0     9.1   48.34   
10              Chicago  110.0      50.6    3344.0     3369.0    10.4   34.44   
11         Indianapolis   28.0      52.3     361.0      746.0     9.7   38.74   
12           Des Moines   17.0      49.0     104.0      201.0    11.2   30.85   
13              Wichita    8.0      56.6     125.0      277.0    12.7   30.58   
14           Louisville   30.0      55.6     291.0      593.0     8.3   43.11   
15          New Orleans    9.0      68.3     204.0      361.0     8.4   56.77   
16            Baltimore   47.0      55.0     625.0      905.0     9.6   41.31   
17              Detroit   35.0      49.9    1064.0     1513.0    10.1   30.96   
18  Minneapolis-St.Paul   29.0      43.5     699.0      744.0    10.6   25.94   
19          Kansas City   14.0      54.5     381.0      507.0    10.0   37.00   
20            St. Louis   56.0      55.9     775.0      622.0     9.5   35.89   
21                Omaha   14.0      51.5     181.0      347.0    10.9   30.18   
22         Alburquerque   11.0      56.8      46.0      244.0     8.9    7.77   
23               Albany   46.0      47.6      44.0      116.0     8.8   33.36   
24              Buffalo   11.0      47.1     391.0      463.0    12.4   36.11   
25           Cincinnati   23.0      54.0     462.0      453.0     7.1   39.04   
26            Cleveland   65.0      49.7    1007.0      751.0    10.9   34.99   
27             Columbus   26.0      51.5     266.0      540.0     8.6   37.01   
28         Philadelphia   69.0      54.6    1692.0     1950.0     9.6   39.93   
29           Pittsburgh   61.0      50.4     347.0      520.0     9.4   36.22   
30           Providence   94.0      50.0     343.0      179.0    10.6   42.75   
31              Memphis   10.0      61.6     337.0      624.0     9.2   49.10   
32            Nashville   18.0      59.4     275.0      448.0     7.9   46.00   
33               Dallas    9.0      66.2     641.0      844.0    10.9   35.94   
34              Houston   10.0      68.9     721.0     1233.0    10.8   48.19   
35       Salt Lake City   28.0      51.0     137.0      176.0     8.7   15.17   
36              Norfolk   31.0      59.3      96.0      308.0    10.6   44.68   
37             Richmond   26.0      57.8     197.0      299.0     7.6   42.59   
38              Seattle   29.0      51.1     379.0      531.0     9.4   38.79   
39           Charleston   31.0      55.2      35.0       71.0     6.5   40.75   
40            Milwaukee   16.0      45.7     569.0      717.0    11.8   29.07   

     Dias  
0    36.0  
1   100.0  
2    67.0  
3    86.0  
4   127.0  
5   114.0  
6   111.0  
7   116.0  
8   128.0  
9   115.0  
10  122.0  
11  121.0  
12  103.0  
13   82.0  
14  123.0  
15  113.0  
16  111.0  
17  129.0  
18  137.0  
19   99.0  
20  105.0  
21   98.0  
22   58.0  
23  135.0  
24  166.0  
25  132.0  
26  155.0  
27  134.0  
28  115.0  
29  147.0  
30  125.0  
31  105.0  
32  119.0  
33   78.0  
34  103.0  
35   89.0  
36  116.0  
37  115.0  
38  164.0  
39  148.0  
40  123.0

In [28]:
#for i in df:
   # df.rename(index={i:df['Ciudad']})
ciudades=df.iloc[:,1:8]
ciudades

SO2  Neg.Temp  Empresas  Poblacion  Viento  Precip   Dias
0    10.0      70.3     213.0      582.0     6.0    7.05   36.0
1    13.0      61.0      91.0      132.0     8.2   48.52  100.0
2    12.0      56.7     453.0      716.0     8.7   20.66   67.0
3    17.0      51.9     454.0      515.0     9.0   12.95   86.0
4    56.0      49.1     412.0      158.0     9.0   43.37  127.0
5    36.0      54.0      80.0       80.0     9.0   40.25  114.0
6    29.0      57.3     434.0      757.0     9.3   38.89  111.0
7    14.0      68.4     136.0      529.0     8.8   54.47  116.0
8    10.0      75.5     207.0      335.0     9.0   59.80  128.0
9    24.0      61.5     368.0      497.0     9.1   48.34  115.0
10  110.0      50.6    3344.0     3369.0    10.4   34.44  122.0
11   28.0      52.3     361.0      746.0     9.7   38.74  121.0
12   17.0      49.0     104.0      201.0    11.2   30.85  103.0
13    8.0      56.6     125.0      277.0    12.7   30.58   82.0
14   30.0      55.6     291.0      593.0     8.3   43.11  123.0
15    9.0      68.3     204.0      361.0     8.4   56.77  113.0
16   47.0      55.0     625.0      905.0     9.6   41.31  111.0
17   35.0      49.9    1064.0     1513.0    10.1   30.96  129.0
18   29.0      43.5     699.0      744.0    10.6   25.94  137.0
19   14.0      54.5     381.0      507.0    10.0   37.00   99.0
20   56.0      55.9     775.0      622.0     9.5   35.89  105.0
21   14.0      51.5     181.0      347.0    10.9   30.18   98.0
22   11.0      56.8      46.0      244.0     8.9    7.77   58.0
23   46.0      47.6      44.0      116.0     8.8   33.36  135.0
24   11.0      47.1     391.0      463.0    12.4   36.11  166.0
25   23.0      54.0     462.0      453.0     7.1   39.04  132.0
26   65.0      49.7    1007.0      751.0    10.9   34.99  155.0
27   26.0      51.5     266.0      540.0     8.6   37.01  134.0
28   69.0      54.6    1692.0     1950.0     9.6   39.93  115.0
29   61.0      50.4     347.0      520.0     9.4   36.22  147.0
30   94.0      50.0     343.0      179.0    10.6   42.75  125.0
31   10.0      61.6     337.0      624.0     9.2   49.10  105.0
32   18.0      59.4     275.0      448.0     7.9   46.00  119.0
33    9.0      66.2     641.0      844.0    10.9   35.94   78.0
34   10.0      68.9     721.0     1233.0    10.8   48.19  103.0
35   28.0      51.0     137.0      176.0     8.7   15.17   89.0
36   31.0      59.3      96.0      308.0    10.6   44.68  116.0
37   26.0      57.8     197.0      299.0     7.6   42.59  115.0
38   29.0      51.1     379.0      531.0     9.4   38.79  164.0
39   31.0      55.2      35.0       71.0     6.5   40.75  148.0
40   16.0      45.7     569.0      717.0    11.8   29.07  123.0

In [29]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
df_transformed = ss.fit_transform(ciudades)
df_transformed

array([[-8.64758344e-01,  2.03621325e+00, -4.49363246e-01,
        -4.65199774e-02, -2.44055543e+00, -2.55601170e+00,
        -2.97551354e+00],
       [-7.35360198e-01,  7.33515074e-01, -6.68566966e-01,
        -8.33223536e-01, -8.81503731e-01,  1.01065334e+00,
        -5.31008991e-01],
       [-7.78492913e-01,  1.31192263e-01, -1.81428110e-02,
         1.87742860e-01, -5.27173800e-01, -1.38547128e+00,
        -1.79145665e+00],
       [-5.62829336e-01, -5.41168084e-01, -1.63460592e-02,
        -1.63651396e-01, -3.14575841e-01, -2.04857684e+00,
        -1.06574436e+00],
       [ 1.11934657e+00, -9.33378287e-01, -9.18096352e-02,
        -7.87769553e-01, -3.14575841e-01,  5.67722907e-01,
         5.00266365e-01],
       [ 2.56692258e-01, -2.47010432e-01, -6.88331236e-01,
        -9.24131503e-01, -3.14575841e-01,  2.99384471e-01,
         3.72637888e-03],
       [-4.52367503e-02,  2.15237306e-01, -5.22810954e-02,
         2.59420295e-01, -1.01977883e-01,  1.82416435e-01,
        -1.1085977

In [34]:
from numpy import linalg as LA
cov_mat=df.cov()
Prueba=LA.eig(cov_mat)
Prueba
#Pregunta en clase, sobre lo que pide en el apartado 1 y el apartado 2
#es lo q tu quieras


(array([6.38471962e+05, 1.48120379e+04, 7.01959940e+02, 2.05001941e+02,
        1.16704681e+02, 1.20570493e+01, 1.44870440e+00]),
 array([[-1.68607518e-02,  9.98356252e-02,  2.08775573e-01,
         -9.58831063e-01,  1.52191203e-01,  5.39529110e-02,
         -2.70413759e-02],
        [ 1.14177937e-03, -2.58143904e-02, -7.16007449e-02,
          1.10147840e-01,  4.77854201e-01,  8.52534945e-01,
         -1.64050698e-01],
        [-6.96832794e-01,  7.10249079e-01, -6.71822007e-02,
          7.31978785e-02,  9.64365414e-03,  2.15302321e-03,
          1.13620790e-03],
        [-7.17028451e-01, -6.92912523e-01,  5.66669352e-02,
         -4.90666865e-02, -1.07354573e-02, -2.91575116e-03,
         -5.68200558e-05],
        [-4.06752976e-04,  1.01168043e-03,  5.38660645e-03,
          1.50660878e-02, -2.54019170e-02, -1.76541256e-01,
         -9.83834710e-01],
        [ 4.33692181e-04, -1.22593675e-03,  2.65807619e-01,
          1.62617123e-01,  8.32729325e-01, -4.53206155e-01,
          6.376